// Generated by package.py; edit shared/model.js and bridge.js.
(() => {
  const fields = ["followers", "following", "followsYou", "youFollow"];
  const number = (value) =>
    Number.isSafeInteger(value) && value >= 0 ? value : undefined;
  const boolean = (...values) =>
    values.find((value) => typeof value === "boolean");
  function normalizeUser(raw) {
    if (!raw || typeof raw !== "object") return null;
    const legacy = raw.legacy || raw;
    const handle =
      raw.core?.screen_name || legacy.core?.screen_name || legacy.screen_name;
    const id = raw.rest_id || legacy.id_str;
    if (!id || !/^[a-zA-Z0-9_]{1,15}$/.test(handle || "")) return null;
    if (raw.__typename && raw.__typename !== "User") return null;
    const rel = raw.relationship_perspectives || {};
    return {
      id: String(id),
      handle: handle.toLowerCase(),
      followers: number(raw.relationship_counts?.followers) ?? number(legacy.followers_count),
      following: number(raw.relationship_counts?.following) ?? number(legacy.friends_count),
      followsYou: boolean(rel.followed_by, legacy.followed_by),
      youFollow: boolean(rel.following, legacy.following),
    };
  }
  function collectUsers(root) {
    const users = new Map(),
      stack = [root];
    let visited = 0;
    while (stack.length && visited++ < 100000) {
      const value = stack.pop();
      if (!value || typeof value !== "object") continue;
      const user = normalizeUser(value);
      if (user) {
        const old = users.get(user.handle);
        const merged = old?.id === user.id ? { ...old } : {};
        for (const [key, val] of Object.entries(user))
          if (val !== undefined) merged[key] = val;
        users.set(user.handle, merged);
      }
      for (const child of Object.values(value))
        if (child && typeof child === "object") stack.push(child);
    }
    return [...users.values()];
  }
  class UserCache {
    constructor(freshFor = 300000, limit = 3000) {
      this.freshFor = freshFor;
      this.limit = limit;
      this.entries = new Map();
    }
    clear() {
      this.entries.clear();
    }
    put(user, now = Date.now()) {
      if (
        !user ||
        !/^[a-z0-9_]{1,15}$/.test(user.handle || "") ||
        typeof user.id !== "string"
      )
        return;
      let entry = this.entries.get(user.handle);
      if (entry?.id !== user.id)
        entry = { id: user.id, handle: user.handle, times: {} };
      for (const field of fields) {
        const value = user[field];
        if (
          field === "followers" || field === "following"
            ? number(value) !== undefined
            : typeof value === "boolean"
        ) {
          entry[field] = value;
          entry.times[field] = now;
        }
      }
      this.entries.delete(user.handle);
      this.entries.set(user.handle, entry);
      while (this.entries.size > this.limit)
        this.entries.delete(this.entries.keys().next().value);
    }
    get(handle, now = Date.now()) {
      const entry = this.entries.get(handle.toLowerCase());
      if (!entry) return null;
      // X can prefetch a timeline long before its virtual rows are displayed.
      // Age marks a snapshot as stale; it must not erase already observed data.
      this.entries.delete(entry.handle);
      this.entries.set(entry.handle, entry);
      const result = { id: entry.id, handle: entry.handle, stale: {} };
      for (const field of fields) {
        if (entry[field] === undefined) continue;
        result[field] = entry[field];
        result.stale[field] = now - entry.times[field] >= this.freshFor;
      }
      return result;
    }
  }
  globalThis.XXModel = { normalizeUser, collectUsers, UserCache };
})();

(() => {
  if (window.__xxBridgeInstalled) return;
  window.__xxBridgeInstalled = true;
  // Cookies stay in this world. Only an opaque generation reaches the UI.
  const signature = () =>
    document.cookie
      .split(";")
      .map((s) => s.trim())
      .filter((s) => /^(twid|ct0)=/.test(s))
      .sort()
      .join(";");
  let identity = signature(),
    epoch = 0;
  const emit = (users) =>
    window.postMessage(
      { source: "xx-passive-v1", epoch, users },
      location.origin,
    );
  const sync = () => {
    const next = signature();
    if (next !== identity) {
      identity = next;
      epoch++;
      emit([]);
    }
    return epoch;
  };
  setInterval(sync, 1000);
  const eligible = (input) => {
    try {
      const url = new URL(input, location.href);
      return (
        ["x.com", "twitter.com", "api.x.com", "api.twitter.com"].includes(
          url.hostname,
        ) && /\/(graphql|2|1\.1)\//.test(url.pathname)
      );
    } catch {
      return false;
    }
  };
  const accept = (body, generation) => {
    if (sync() !== generation) return;
    try {
      const users = XXModel.collectUsers(body);
      if (users.length) emit(users);
    } catch {}
  };
  const originalFetch = window.fetch;
  window.fetch = function (...args) {
    const generation = sync();
    const result = Reflect.apply(originalFetch, this, args);
    if (
      eligible(
        typeof args[0] === "string" || args[0] instanceof URL
          ? args[0]
          : args[0]?.url,
      )
    ) {
      result
        .then((response) => {
          if (
            !response.ok ||
            !response.headers.get("content-type")?.includes("json")
          )
            return;
          response
            .clone()
            .json()
            .then((body) => accept(body, generation))
            .catch(() => {});
        })
        .catch(() => {});
    }
    return result;
  };
  const originalOpen = XMLHttpRequest.prototype.open,
    originalSend = XMLHttpRequest.prototype.send;
  const requests = new WeakMap();
  XMLHttpRequest.prototype.open = function (method, url, ...rest) {
    requests.set(this, eligible(url));
    return Reflect.apply(originalOpen, this, [method, url, ...rest]);
  };
  XMLHttpRequest.prototype.send = function (...args) {
    const generation = sync();
    if (requests.get(this))
      this.addEventListener(
        "load",
        () => {
          try {
            if (this.status < 200 || this.status >= 300) return;
            const body =
              this.responseType === "json"
                ? this.response
                : JSON.parse(this.responseText);
            accept(body, generation);
          } catch {}
        },
        { once: true },
      );
    return Reflect.apply(originalSend, this, args);
  };
})();
