"""Build a dependency-free load-unpacked distribution ZIP."""
from pathlib import Path
import zipfile
import json
root=Path(__file__).resolve().parent
# Chrome deduplicates identical content-script paths across execution worlds.
# Give the MAIN world its own bundle; keep model.js available to ISOLATED.
(root/'bridge-main.js').write_text('// Generated by package.py; edit shared/model.js and bridge.js.\n'+
    (root/'shared/model.js').read_text()+'\n'+(root/'bridge.js').read_text())
version=json.loads((root/'manifest.json').read_text())['version']
out=root/'dist';out.mkdir(exist_ok=True)
with zipfile.ZipFile(out/f'xx-extension-{version}.zip','w',zipfile.ZIP_DEFLATED) as z:
    for pattern in ['*.js','*.html','*.css','manifest.json','shared/*.js','icons/*.png','_locales/*/*.json']:
        for file in sorted(root.glob(pattern)):
            z.write(file,file.relative_to(root))
print(out/f'xx-extension-{version}.zip')
