import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("execution worlds use distinct paths and the MAIN bundle is current", () => {
  const manifest = JSON.parse(read("manifest.json"));
  const main = manifest.content_scripts.find((entry) => entry.world === "MAIN");
  const isolated = manifest.content_scripts.find((entry) => entry.world === "ISOLATED");
  assert.equal(main.js.some((path) => isolated.js.includes(path)), false);
  assert.equal(read("bridge-main.js"),
    "// Generated by package.py; edit shared/model.js and bridge.js.\n" +
    read("shared/model.js") + "\n" + read("bridge.js"));
});
